### ISSUE TITLE
Crash on Linux when joining game

### ISSUE THREAD

**Issue by SlenLen** [Plag0/Soundproof-Walls#1] opened 2024-02-12 15:39 UTC
When using the native Linux version of Barotruma, the mod currently causes a crash whenever you try to join a game.
Singeplayer crashes on the loading screen while Multiplayer crashes in the main menu during the "Connecting" message.

I attached a log, but I'm not knowledgeable enough myself to take a guess as to what the issue is. Might be wrong about this, but I think the multiplayer crash is even separate from the singleplayer crash as the stacktrace mentions Networking methods, and I don't think these would be relevant during singeplayer.
[servercrashreport.log](https://github.com/Plag0/Soundproof-Walls/files/14240399/servercrashreport.3.log)

**Comment by Plag0** [comment] 2024-02-12 17:40
Thank you for reporting this issue and including the log! My environment is not set up to debug for Linux at the moment, and I will be away for the next few days, so I will start working on a fix for this over the weekend. In the meantime, can you attach the crash log for singleplayer? Thank you :)

**Comment by SlenLen** [comment] 2024-02-17 01:54
Sorry for the late reply. As far as I'm aware, Singleplayer doesn't have crash reports. At least no new files get created when the game crashes.

The Barotrauma process terminates with the error
```
terminate called after throwing an instance of 'PAL_SEHException'
IOT instruction (core dumped)
```
so not really a lot of information there...

**Comment by Plag0** [comment] 2024-02-17 18:15
This issue has now been fixed. No crash report was generated because the game was crashing before anything loaded due to a rare issue with what seems to be MonoMod: https://github.com/dotnet/runtime/issues/78271.

The cause of this exception was the line of code responsible for creating the "Listening..." text being compiled in the Linux DLL. 
```
font.DrawString(spriteBatch, text, position, color, 0, Vector2.Zero, cam.Zoom / size, 0, 0.001f, Alignment.Center);
```
Since this issue seems mostly out of my control, the current solution is simply to remove that text for Linux users.
Thank you for your commitment to improving the mod and opening this issue, I really appreciate it! 👍

**Closed as completed by Plag0** 2024-02-17 18:15 UTC
